# AUGMENTATION: True
# IMAGE_SIZE: [224, 224, 3] #As per ResNet50 Model
# INCLUDE_TOP: False
# WEIGHTS: imagenet'
EPOCHS: 1
BATCH_SIZE: 128
LEARNING_RATE: 0.0001
IMAGE_SIZE: [256, 64, 1]

TRAIN_SIZE: 30000
VALID_SIZE: 3000