artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: D:/Document/GitHub/write_io_dataset.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_pre_processing:
  train_size: 30
  validation_size: 10
  resize_width: 256
  resize_height: 64
  file_path_training: D:/Document/GitHub/write.io/artifacts/data_ingestion/data.zip/written_name_train_v2.csv
  file_path_validation: D:/Document/GitHub/write.io/artifacts/data_ingestion/data.zip/written_name_validation_v2.csv
  image_path_training: D:/Document/GitHub/write.io/artifacts/data_ingestion/data.zip/train_v2/train/
  image_path_validation: D:/Document/GitHub/write.io/artifacts/data_ingestion/data.zip/validation_v2/validation/

prepare_base_model:
  alphabets: "ABCDEFGHIJKLMNOPQRSTUVWXYZ-' "
  max_str_len: 24
  num_of_timestamps: 64

build_model:
  root_dir: D:/Document/GitHub/write.io/artifacts/model
  model_path: D:/Document/GitHub/write.io/artifacts/model/model.keras